--! ------------------------------------------------------------
--!  Do not edit this file, it was created by ada-merge from:
--!     bssnbase-constraints.adt
--! ------------------------------------------------------------
-- src: ./bssnbase-constraints.adt
package body BSSNBase.Constraints is

   dxdx, dydy, dzdz : Real;
   two_dx, two_dy, two_dz : Real;
   four_dxdy, four_dxdz, four_dydz : Real;

   procedure set_constraints (point : GridPoint) is

-- beg: ./include/local-data.ad --------------------------------------------------------------------
   -- these are local variables used by the basic codes such as dot-gab.ad, dot-kab.ad etc.
   -- renames are good as they don't involve a memory copy

   ----------------------------------------------------------------------
   -- basic local data

   N         : Real;                                     -- lapse
   phi       : Real;                                     -- conformal factor
   trK       : Real;                                     -- trace of K
   Gi        : GammaPointArray;                          -- trace of conformal connection, GammaBar^{i}
   gBar      : MetricPointArray;                         -- gBar_{ab}
   iBar      : MetricPointArray;                         -- gBar^{ab}
   ABar      : ExtcurvPointArray;                        -- ABar_{ab}
   BBar      : ExtcurvPointArray;                        -- ABar^{ab}

   ----------------------------------------------------------------------
   -- time derivatives of local data

   dot_N     : Real;
   dot_phi   : Real;
   dot_trK   : Real;
   dot_Gi    : GammaPointArray;
   dot_gBar  : MetricPointArray;
   dot_ABar  : ExtcurvPointArray;

   ----------------------------------------------------------------------
   -- partial derivatives of local data

   d1N       : Array (1..3) of Real;                     -- 1st & 2nd derivs of N
   d2N       : Array (symmetric) of Real;

   d1phi     : Array (1..3) of Real;                     -- 1st & 2nd derivs of phi
   d2phi     : Array (symmetric) of Real;

   d1trK     : Array (1..3) of Real;                     -- 1st derivs of trK

   d1Gi      : Array (1..3) of GammaPointArray;          -- 1st derivs of GammaBar^i

   d1gBar    : Array (1..3) of MetricPointArray;         -- 1st & 2nd derivs of gBar_{ab}
   d2gBar    : Array (symmetric) of MetricPointArray;

   d1iBar    : Array (1..3) of MetricPointArray;         -- 1st derivs of gBar^{ab}

   d1ABar    : Array (1..3) of ExtcurvPointArray;        -- 1st derivs of ABar_{ab}

   ----------------------------------------------------------------------
   -- miscellaneous data

   R         : Real;                                     -- Ricci scalar
   Rab       : Array (symmetric) of Real;                -- Ricci tensor

   ----------------------------------------------------------------------
   -- constraints

   Ham       : Real;                                     -- Hamiltonian constraint
   Mom       : MomConstraintPointArray;                  -- Momentum constraints

   ----------------------------------------------------------------------
   -- mappings between the Cadabra and Ada objects
   -- LCB: the following renames could be eliminated by using a set of sed-scripts
   --      to substitute the symbols in the foo.ad files

   -- \partial_{a}{\phi} --> dphi_{a} --> phia --> phi_a --> d1phi (a)

   phi_x : Real renames d1phi (1);
   phi_y : Real renames d1phi (2);
   phi_z : Real renames d1phi (3);

   -- \partial_{a b}{\phi} --> dphi_{a b} --> phiab --> phi_ab --> d2phi (ab)

   phi_xx : Real renames d2phi (xx);
   phi_xy : Real renames d2phi (xy);
   phi_xz : Real renames d2phi (xz);
   phi_yy : Real renames d2phi (yy);
   phi_yz : Real renames d2phi (yz);
   phi_zz : Real renames d2phi (zz);

   -- \partial_{a}{trK} --> d1trK_{a} --> trKa --> trK_a --> d1trK (a)

   trK_x : Real renames d1trK (1);
   trK_y : Real renames d1trK (2);
   trK_z : Real renames d1trK (3);

   -- GammaBar^{a} --> Gia --> Gi_a --> Gi (a)

   Gi_x : Real renames Gi (1);
   Gi_y : Real renames Gi (2);
   Gi_z : Real renames Gi (3);

   -- \partial_{a}{GammaBar^{b}} --> dGi^{b}_{a} --> Giba --> Gi_ba --> d1Gi (a)(b)

   Gi_xx : Real renames d1Gi (1)(1);
   Gi_xy : Real renames d1Gi (2)(1);
   Gi_xz : Real renames d1Gi (3)(1);

   Gi_yx : Real renames d1Gi (1)(2);
   Gi_yy : Real renames d1Gi (2)(2);
   Gi_yz : Real renames d1Gi (3)(2);

   Gi_zx : Real renames d1Gi (1)(3);
   Gi_zy : Real renames d1Gi (2)(3);
   Gi_zz : Real renames d1Gi (3)(3);

   -- \partial_{a}{N} --> dN_{a} --> Na --> N_a --> d1N (a)

   N_x : Real renames d1N (1);
   N_y : Real renames d1N (2);
   N_z : Real renames d1N (3);

   -- \partial_{a b}{N} --> dN_{a b} --> Nab --> N_ab --> d2N (ab)

   N_xx : Real renames d2N (xx);
   N_xy : Real renames d2N (xy);
   N_xz : Real renames d2N (xz);
   N_yy : Real renames d2N (yy);
   N_yz : Real renames d2N (yz);
   N_zz : Real renames d2N (zz);

   -- R_{a b} --> Rab --> Rab (ab)

   Rxx : Real renames Rab (xx);
   Rxy : Real renames Rab (xy);
   Rxz : Real renames Rab (xz);
   Ryy : Real renames Rab (yy);
   Ryz : Real renames Rab (yz);
   Rzz : Real renames Rab (zz);

   -- ABar_{a b} --> ABarab --> ABar_ab --> ABar (ab)

   ABar_xx : Real Renames ABar (xx);
   ABar_xy : Real Renames ABar (xy);
   ABar_xz : Real Renames ABar (xz);
   ABar_yy : Real Renames ABar (yy);
   ABar_yz : Real Renames ABar (yz);
   ABar_zz : Real Renames ABar (zz);

   -- ABar^{a b} --> BBarab --> BBar_ab --> BBar (ab)

   BBar_xx : Real Renames BBar (xx);
   BBar_xy : Real Renames BBar (xy);
   BBar_xz : Real Renames BBar (xz);
   BBar_yy : Real Renames BBar (yy);
   BBar_yz : Real Renames BBar (yz);
   BBar_zz : Real Renames BBar (zz);

   -- gBar_{a b} --> gBarab --> gBar_ab --> gBar (ab)

   gBar_xx : Real Renames gBar (xx);
   gBar_xy : Real Renames gBar (xy);
   gBar_xz : Real Renames gBar (xz);
   gBar_yy : Real Renames gBar (yy);
   gBar_yz : Real Renames gBar (yz);
   gBar_zz : Real Renames gBar (zz);

   -- gBar^{a b} --> iBarab --> iBar_ab --> iBar (ab)

   iBar_xx : Real renames iBar (xx);
   iBar_xy : Real renames iBar (xy);
   iBar_xz : Real renames iBar (xz);
   iBar_yy : Real renames iBar (yy);
   iBar_yz : Real renames iBar (yz);
   iBar_zz : Real renames iBar (zz);

   -- \partial_{a}{gBar_{b c}} --> dgBar_{b c a} --> gBarbca --> gBar_bca --> d1gBar(a)(bc)

   gBar_xxx : Real renames d1gBar (1)(xx);
   gBar_xxy : Real renames d1gBar (2)(xx);
   gBar_xxz : Real renames d1gBar (3)(xx);

   gBar_xyx : Real renames d1gBar (1)(xy);
   gBar_xyy : Real renames d1gBar (2)(xy);
   gBar_xyz : Real renames d1gBar (3)(xy);

   gBar_xzx : Real renames d1gBar (1)(xz);
   gBar_xzy : Real renames d1gBar (2)(xz);
   gBar_xzz : Real renames d1gBar (3)(xz);

   gBar_yyx : Real renames d1gBar (1)(yy);
   gBar_yyy : Real renames d1gBar (2)(yy);
   gBar_yyz : Real renames d1gBar (3)(yy);

   gBar_yzx : Real renames d1gBar (1)(yz);
   gBar_yzy : Real renames d1gBar (2)(yz);
   gBar_yzz : Real renames d1gBar (3)(yz);

   gBar_zzx : Real renames d1gBar (1)(zz);
   gBar_zzy : Real renames d1gBar (2)(zz);
   gBar_zzz : Real renames d1gBar (3)(zz);

   -- \partial_{a}{gBar^{b c}} --> dgBar^{b c}_{a} --> iBarbca --> iBar_bca --> d1iBar(a)(bc)

   iBar_xxx : Real renames d1iBar (1)(xx);
   iBar_xxy : Real renames d1iBar (2)(xx);
   iBar_xxz : Real renames d1iBar (3)(xx);

   iBar_xyx : Real renames d1iBar (1)(xy);
   iBar_xyy : Real renames d1iBar (2)(xy);
   iBar_xyz : Real renames d1iBar (3)(xy);

   iBar_xzx : Real renames d1iBar (1)(xz);
   iBar_xzy : Real renames d1iBar (2)(xz);
   iBar_xzz : Real renames d1iBar (3)(xz);

   iBar_yyx : Real renames d1iBar (1)(yy);
   iBar_yyy : Real renames d1iBar (2)(yy);
   iBar_yyz : Real renames d1iBar (3)(yy);

   iBar_yzx : Real renames d1iBar (1)(yz);
   iBar_yzy : Real renames d1iBar (2)(yz);
   iBar_yzz : Real renames d1iBar (3)(yz);

   iBar_zzx : Real renames d1iBar (1)(zz);
   iBar_zzy : Real renames d1iBar (2)(zz);
   iBar_zzz : Real renames d1iBar (3)(zz);

   -- \partial_{a}{ABar_{b c}} --> dABar_{b c a} --> ABarbca --> ABar_bca --> d1ABar(a)(bc)

   ABar_xxx : Real renames d1ABar (1)(xx);
   ABar_xxy : Real renames d1ABar (2)(xx);
   ABar_xxz : Real renames d1ABar (3)(xx);

   ABar_xyx : Real renames d1ABar (1)(xy);
   ABar_xyy : Real renames d1ABar (2)(xy);
   ABar_xyz : Real renames d1ABar (3)(xy);

   ABar_xzx : Real renames d1ABar (1)(xz);
   ABar_xzy : Real renames d1ABar (2)(xz);
   ABar_xzz : Real renames d1ABar (3)(xz);

   ABar_yyx : Real renames d1ABar (1)(yy);
   ABar_yyy : Real renames d1ABar (2)(yy);
   ABar_yyz : Real renames d1ABar (3)(yy);

   ABar_yzx : Real renames d1ABar (1)(yz);
   ABar_yzy : Real renames d1ABar (2)(yz);
   ABar_yzz : Real renames d1ABar (3)(yz);

   ABar_zzx : Real renames d1ABar (1)(zz);
   ABar_zzy : Real renames d1ABar (2)(zz);
   ABar_zzz : Real renames d1ABar (3)(zz);

   -- \partial_{a b}{gBar_{c d}} --> dgBar_{c d a b} --> gBarcdab --> gBar_cdab --> d2gBar(ab)(cd)

   gBar_xxxx : Real renames d2gBar (xx)(xx);
   gBar_xyxx : Real renames d2gBar (xx)(xy);
   gBar_xzxx : Real renames d2gBar (xx)(xz);
   gBar_yyxx : Real renames d2gBar (xx)(yy);
   gBar_yzxx : Real renames d2gBar (xx)(yz);
   gBar_zzxx : Real renames d2gBar (xx)(zz);

   gBar_xxxy : Real renames d2gBar (xy)(xx);
   gBar_xyxy : Real renames d2gBar (xy)(xy);
   gBar_xzxy : Real renames d2gBar (xy)(xz);
   gBar_yyxy : Real renames d2gBar (xy)(yy);
   gBar_yzxy : Real renames d2gBar (xy)(yz);
   gBar_zzxy : Real renames d2gBar (xy)(zz);

   gBar_xxxz : Real renames d2gBar (xz)(xx);
   gBar_xyxz : Real renames d2gBar (xz)(xy);
   gBar_xzxz : Real renames d2gBar (xz)(xz);
   gBar_yyxz : Real renames d2gBar (xz)(yy);
   gBar_yzxz : Real renames d2gBar (xz)(yz);
   gBar_zzxz : Real renames d2gBar (xz)(zz);

   gBar_xxyy : Real renames d2gBar (yy)(xx);
   gBar_xyyy : Real renames d2gBar (yy)(xy);
   gBar_xzyy : Real renames d2gBar (yy)(xz);
   gBar_yyyy : Real renames d2gBar (yy)(yy);
   gBar_yzyy : Real renames d2gBar (yy)(yz);
   gBar_zzyy : Real renames d2gBar (yy)(zz);

   gBar_xxyz : Real renames d2gBar (yz)(xx);
   gBar_xyyz : Real renames d2gBar (yz)(xy);
   gBar_xzyz : Real renames d2gBar (yz)(xz);
   gBar_yyyz : Real renames d2gBar (yz)(yy);
   gBar_yzyz : Real renames d2gBar (yz)(yz);
   gBar_zzyz : Real renames d2gBar (yz)(zz);

   gBar_xxzz : Real renames d2gBar (zz)(xx);
   gBar_xyzz : Real renames d2gBar (zz)(xy);
   gBar_xzzz : Real renames d2gBar (zz)(xz);
   gBar_yyzz : Real renames d2gBar (zz)(yy);
   gBar_yzzz : Real renames d2gBar (zz)(yz);
   gBar_zzzz : Real renames d2gBar (zz)(zz);
-- end: ./include/local-data.ad --------------------------------------------------------------------

-- beg: ./cadabra/ricci.ad -------------------------------------------------------------------------
Procedure set_3d_ricci is
   x0,   x1,   x2,   x3,   x4,   x5,   x6,   x7,   x8,   x9,   x10,  x11,  x12,  x13,  
   x14,  x15,  x16,  x17,  x18,  x19,  x20,  x21,  x22,  x23,  x24,  x25,  x26,  x27,  
   x28,  x29,  x30,  x31,  x32,  x33,  x34,  x35,  x36,  x37,  x38,  x39,  x40,  x41,  
   x42,  x43,  x44,  x45,  x46,  x47,  x48,  x49,  x50,  x51,  x52,  x53,  x54,  x55,  
   x56,  x57,  x58,  x59,  x60,  x61,  x62,  x63,  x64,  x65,  x66,  x67,  x68,  x69,  
   x70,  x71,  x72,  x73,  x74,  x75,  x76,  x77,  x78,  x79,  x80,  x81,  x82,  x83,  
   x84,  x85,  x86,  x87,  x88,  x89,  x90,  x91,  x92,  x93,  x94,  x95,  x96,  x97,  
   x98,  x99,  x100, x101, x102, x103, x104, x105, x106, x107, x108, x109, x110, x111, 
   x112, x113, x114, x115, x116, x117, x118, x119, x120, x121, x122, x123, x124, x125, 
   x126, x127, x128, x129, x130, x131, x132, x133, x134, x135, x136, x137, x138, x139, 
   x140, x141, x142, x143, x144, x145, x146, x147, x148, x149, x150, x151, x152, x153, 
   x154, x155, x156, x157, x158, x159, x160, x161, x162, x163, x164, x165, x166, x167, 
   x168, x169, x170, x171, x172, x173, x174, x175, x176, x177, x178, x179, x180, x181, 
   x182, x183, x184, x185, x186, x187, x188, x189, x190, x191, x192, x193, x194, x195, 
   x196, x197, x198, x199, x200, x201, x202, x203, x204, x205, x206, x207, x208, x209, 
   x210, x211, x212, x213, x214, x215, x216, x217, x218, x219, x220, x221, x222, x223, 
   x224, x225, x226, x227, x228, x229, x230, x231, x232, x233, x234, x235, x236, x237, 
   x238, x239, x240, x241, x242, x243, x244, x245, x246, x247, x248, x249, x250 : Real;
   x251, x252, x253, x254, x255, x256, x257, x258, x259, x260, x261, x262, x263, x264, 
   x265, x266, x267, x268, x269, x270, x271, x272, x273 : Real;
begin
   x0   := 2.0*phi_xx;
   x1   := (1.0/2.0)*iBar_xx;
   x2   := (1.0/2.0)*iBar_yy;
   x3   := (1.0/2.0)*iBar_zz;
   x4   := (1.0/2.0)*gBar_xyx;
   x5   := (1.0/2.0)*iBar_xzx;
   x6   := (1.0/4.0)*iBar_yyx;
   x7   := (1.0/2.0)*iBar_yzx;
   x8   := (1.0/4.0)*iBar_zzx;
   x9   := iBar_xx*phi_x;
   x10  := iBar_xy*phi_y;
   x11  := iBar_xz*phi_z;
   x12  := 12.0*(phi_x ** 2);
   x13  := gBar_xx*iBar_xx;
   x14  := 4.0*gBar_xx;
   x15  := iBar_xy*phi_xy;
   x16  := iBar_xz*phi_xz;
   x17  := 2.0*phi_yy;
   x18  := gBar_xx*iBar_yy;
   x19  := iBar_yz*phi_yz;
   x20  := 2.0*phi_zz;
   x21  := gBar_xx*iBar_zz;
   x22  := iBar_xy*phi_x;
   x23  := iBar_yy*phi_y;
   x24  := iBar_yz*phi_z;
   x25  := iBar_xz*phi_x;
   x26  := iBar_yz*phi_y;
   x27  := iBar_zz*phi_z;
   x28  := 2.0*gBar_xyx;
   x29  := 2.0*gBar_xzx;
   x30  := gBar_xxy*iBar_yz;
   x31  := iBar_xx*x30;
   x32  := gBar_xyz*iBar_xy;
   x33  := gBar_xxy*iBar_xz;
   x34  := gBar_xzx*iBar_xy;
   x35  := iBar_yy*x33;
   x36  := gBar_xxz*iBar_xz;
   x37  := gBar_xyx*iBar_xy;
   x38  := gBar_xxz*iBar_zz;
   x39  := gBar_xzy*iBar_yz;
   x40  := gBar_xyz*iBar_xz;
   x41  := gBar_xyx*iBar_yy;
   x42  := gBar_xzx*iBar_yz;
   x43  := gBar_xyx*iBar_xx;
   x44  := (iBar_xy ** 2);
   x45  := gBar_xxy*gBar_xyx;
   x46  := (iBar_xz ** 2);
   x47  := gBar_xxz*gBar_xzx;
   x48  := (iBar_yz ** 2);
   x49  := gBar_xyz*gBar_xzy;
   x50  := 24.0*gBar_xx;
   x51  := phi_x*x50;
   x52  := phi_y*x24;
   x53  := iBar_xx*iBar_yy;
   x54  := gBar_xzy*iBar_xy;
   x55  := gBar_xxz*iBar_yz;
   x56  := gBar_xyz*iBar_yz;
   x57  := iBar_xx*iBar_zz;
   x58  := gBar_xyx*iBar_yz;
   x59  := gBar_xyx*iBar_xz;
   x60  := gBar_xzy*iBar_xz;
   x61  := iBar_zz*x32;
   x62  := iBar_yy*iBar_zz;
   x63  := gBar_xzx*x39;
   x64  := iBar_xxx + iBar_xyy + iBar_xzz;
   x65  := (1.0/2.0)*gBar_xxx;
   x66  := iBar_xyx + iBar_yyy + iBar_yzz;
   x67  := (1.0/2.0)*gBar_xxy;
   x68  := iBar_xzx + iBar_yzy + iBar_zzz;
   x69  := (1.0/2.0)*gBar_xxz;
   x70  := 12.0*(phi_y ** 2);
   x71  := 12.0*(phi_z ** 2);
   x72  := (gBar_xxy ** 2);
   x73  := iBar_yy*x1;
   x74  := (gBar_xxz ** 2);
   x75  := iBar_zz*x1;
   x76  := (gBar_xyx ** 2);
   x77  := (gBar_xyz ** 2);
   x78  := iBar_zz*x2;
   x79  := (gBar_xzx ** 2);
   x80  := (gBar_xzy ** 2);
   x81  := (1.0/2.0)*x44;
   x82  := (1.0/2.0)*x46;
   x83  := (1.0/2.0)*x48;
   x84  := 2.0*gBar_xx;
   x85  := phi_x*x64;
   x86  := phi_y*x66;
   x87  := phi_z*x68;
   x88  := (1.0/2.0)*gBar_xzx;
   x89  := (1.0/4.0)*iBar_xxx;
   x90  := (1.0/2.0)*gBar_xy;
   x91  := (1.0/2.0)*gBar_xx;
   x92  := (1.0/2.0)*Gi_yx;
   x93  := (1.0/2.0)*Gi_zx;
   x94  := (1.0/2.0)*gBar_xz;
   x95  := 12.0*phi_x;
   x96  := (1.0/2.0)*gBar_xyy;
   x97  := (1.0/2.0)*gBar_xyz;
   x98  := (1.0/2.0)*gBar_xzy;
   x99  := (1.0/2.0)*gBar_xzz;
   x100 := (1.0/2.0)*iBar_xyx;
   x101 := (1.0/2.0)*gBar_yzz;
   x102 := gBar_yyx*x44;
   x103 := gBar_yzx*x46;
   x104 := gBar_xyy*x44;
   x105 := gBar_xzx*x82;
   x106 := gBar_xyz*x83;
   x107 := gBar_xzy*x83;
   x108 := iBar_xy*x3;
   x109 := gBar_xy*iBar_xx;
   x110 := gBar_xy*iBar_yy;
   x111 := gBar_xy*iBar_zz;
   x112 := 4.0*gBar_xy;
   x113 := 2.0*gBar_xy;
   x114 := x46*x69;
   x115 := (1.0/2.0)*iBar_yz;
   x116 := iBar_xz*x115;
   x117 := gBar_xxy*x73;
   x118 := x1*x30;
   x119 := gBar_yyz*iBar_yz;
   x120 := iBar_xy*x67;
   x121 := gBar_yzx*iBar_xz;
   x122 := iBar_xy*x121;
   x123 := iBar_xz*iBar_yy;
   x124 := x123*x67;
   x125 := x1*x55;
   x126 := gBar_xxz*x75;
   x127 := gBar_yyx*iBar_xy;
   x128 := iBar_xz*x69;
   x129 := iBar_xy*iBar_zz;
   x130 := gBar_yyz*x129;
   x131 := gBar_yzy*iBar_yz;
   x132 := iBar_xz*x32;
   x133 := gBar_xyx*x73;
   x134 := x2*x59;
   x135 := x1*x58;
   x136 := iBar_xy*x4;
   x137 := gBar_xyy*x2;
   x138 := gBar_yyx*x2;
   x139 := gBar_xyz*x78;
   x140 := iBar_yz*x97;
   x141 := x1*x42;
   x142 := iBar_xz*x88;
   x143 := gBar_xzx*x75;
   x144 := x3*x34;
   x145 := iBar_yz*x98;
   x146 := gBar_yzx*x3;
   x147 := gBar_xzy*x78;
   x148 := 24.0*gBar_xy;
   x149 := phi_x*x148;
   x150 := gBar_xyy*iBar_xy;
   x151 := x1*x56;
   x152 := iBar_xy*x39;
   x153 := Gi_xx*x90 + Gi_xy*x91 + Gi_yy*x90 + Gi_zy*x94 + gBar_xxy*x10 + gBar_xxy*x11 + gBar_xxy*x9 - gBar_xyx*x151 - gBar_xyxx*x1 - gBar_xyxy*iBar_xy - gBar_xyxz*iBar_xz + gBar_xyy*x117 + gBar_xyy*x125 - gBar_xyy*x133 - gBar_xyy*x141 - gBar_xyyy*x2 - gBar_xyyz*iBar_yz + gBar_xyz*x105 
         - gBar_xyz*x114 + gBar_xyz*x118 + gBar_xyz*x126 - gBar_xyz*x143 - gBar_xyz*x25 - gBar_xyz*x26 - gBar_xyz*x27 - gBar_xyz*x5 - gBar_xyzz*x3 + gBar_xzy*x25 + gBar_xzy*x26 + gBar_xzy*x27 + gBar_yy*x92 - gBar_yyx*x100 - gBar_yyx*x117 - gBar_yyx*x125 + gBar_yyx*x133 
         + gBar_yyx*x141 + gBar_yyx*x22 + gBar_yyx*x23 + gBar_yyx*x24 - gBar_yyz*x106 + gBar_yyz*x107 - gBar_yyz*x124 + gBar_yyz*x134 + gBar_yyz*x139 - gBar_yyz*x144 - gBar_yyz*x147 - gBar_yyz*x7 + gBar_yz*x93 - gBar_yzx*x105 - gBar_yzx*x118 - gBar_yzx*x126 + gBar_yzx*x135 
         + gBar_yzx*x143 + gBar_yzx*x25 + gBar_yzx*x26 + gBar_yzx*x27 - gBar_yzx*x5 + gBar_yzy*x106 - gBar_yzy*x107 + gBar_yzy*x124 - gBar_yzy*x129*x69 - gBar_yzy*x134 - gBar_yzy*x139 + gBar_yzy*x144 + gBar_yzy*x147 - iBar_xxx*x4 - iBar_xyy*x67 + iBar_xz*x34*x96 - iBar_xzy*x69 
         - iBar_yyy*x96 + iBar_yz*x32*x96 - iBar_yzy*x97 - iBar_yzy*x98 - iBar_zzx*x101 - iBar_zzy*x99 - 2.0*phi_xy + phi_y*x95 - x0*x109 - x10*x149 - x102*x4 + x102*x67 + x103*x69 + x104*x4 - x104*x67 - x108*x49 + x108*x77 - x109*x12 - x11*x149 - x110*x17 - x110*x70 
         - x111*x20 - x111*x71 - x112*x15 - x112*x16 - x112*x19 - x113*x85 - x113*x86 - x113*x87 + x116*x49 - x116*x77 + x119*x120 - x119*x128 - x119*x136 + x119*x142 - x120*x131 + x121*x140 - x121*x145 - x122*x4 + x122*x67 + x127*x128 - x127*x140 - x127*x142 
         + x127*x145 + x128*x131 - x128*x150 + x130*x69 + x131*x136 - x131*x142 + x132*x4 - x132*x67 - x137*x40 + x137*x60 + x138*x40 - x138*x60 - x146*x32 + x146*x54 - x148*x52 - x152*x96 - x4*x64 - x66*x96 - x68*x97;
   x154 := (1.0/2.0)*iBar_yyx;
   x155 := gBar_yzx*x44;
   x156 := gBar_zzx*x46;
   x157 := gBar_xzy*x44;
   x158 := iBar_xz*x2;
   x159 := gBar_xz*iBar_xx;
   x160 := gBar_xz*iBar_yy;
   x161 := gBar_xz*iBar_zz;
   x162 := 4.0*gBar_xz;
   x163 := 2.0*gBar_xz;
   x164 := iBar_xy*x115;
   x165 := gBar_yzz*iBar_yz;
   x166 := iBar_xy*iBar_xz;
   x167 := x166*x67;
   x168 := x1*x39;
   x169 := gBar_yzz*x129;
   x170 := gBar_zzy*iBar_yz;
   x171 := x166*x4;
   x172 := x3*x32;
   x173 := gBar_yzx*x2;
   x174 := gBar_zzx*iBar_xz;
   x175 := gBar_xzz*iBar_xz;
   x176 := gBar_yzx*iBar_yz;
   x177 := iBar_xy*x176;
   x178 := x3*x54;
   x179 := 24.0*gBar_xz;
   x180 := phi_x*x179;
   x181 := gBar_zzy*x129;
   x182 := Gi_xx*x94 + Gi_xz*x91 + Gi_yz*x90 + Gi_zz*x94 + gBar_xxz*x10 + gBar_xxz*x11 + gBar_xxz*x168 + gBar_xxz*x9 + gBar_xyz*x22 + gBar_xyz*x23 + gBar_xyz*x24 - gBar_xzxx*x1 - gBar_xzxy*iBar_xy - gBar_xzxz*iBar_xz + gBar_xzy*x117 - gBar_xzy*x133 - gBar_xzy*x22 - gBar_xzy*x23 
         - gBar_xzy*x24 - gBar_xzyy*x2 - gBar_xzyz*iBar_yz + gBar_xzz*x105 - gBar_xzz*x114 + gBar_xzz*x118 + gBar_xzz*x126 - gBar_xzz*x135 - gBar_xzz*x143 - gBar_xzz*x167 + gBar_xzz*x171 + gBar_xzz*x172 - gBar_xzz*x178 - gBar_xzzz*x3 + gBar_yz*x92 - gBar_yzx*x100 - gBar_yzx*x117 
         - gBar_yzx*x125 + gBar_yzx*x133 + gBar_yzx*x141 + gBar_yzx*x22 + gBar_yzx*x23 + gBar_yzx*x24 - gBar_yzy*x154 - gBar_yzz*x106 + gBar_yzz*x107 - gBar_yzz*x124 + gBar_yzz*x134 + gBar_yzz*x139 - gBar_yzz*x144 - gBar_yzz*x147 + gBar_zz*x93 - gBar_zzx*x105 - gBar_zzx*x118 
         - gBar_zzx*x126 + gBar_zzx*x135 + gBar_zzx*x143 + gBar_zzx*x167 - gBar_zzx*x171 - gBar_zzx*x172 + gBar_zzx*x178 + gBar_zzx*x25 + gBar_zzx*x26 + gBar_zzx*x27 - gBar_zzx*x5 + gBar_zzy*x106 - gBar_zzy*x107 + gBar_zzy*x124 - gBar_zzy*x134 - gBar_zzy*x139 + gBar_zzy*x144 
         + gBar_zzy*x147 - gBar_zzy*x7 - iBar_xxx*x88 - iBar_xyx*x98 - iBar_xyz*x67 - iBar_xzz*x69 - iBar_yyz*x96 - iBar_yzz*x97 - iBar_yzz*x98 - iBar_zzz*x99 - 2.0*phi_xz + phi_z*x95 - x0*x159 - x1*x63 - x10*x180 - x11*x180 - x12*x159 + x120*x165 - x120*x170 + x122*x69 
         - x122*x88 - x128*x165 + x128*x170 - x128*x54 - x136*x165 + x136*x170 + x140*x174 - x140*x175 + x142*x165 - x142*x170 + x142*x54 - x145*x174 + x145*x175 - x15*x162 - x155*x4 + x155*x67 + x156*x69 + x157*x4 - x157*x67 - x158*x49 + x158*x80 - x16*x162 
         - x160*x17 - x160*x70 - x161*x20 - x161*x71 - x162*x19 - x163*x85 - x163*x86 - x163*x87 + x164*x49 - x164*x80 + x169*x69 + x173*x40 - x173*x60 - x177*x97 + x177*x98 - x179*x52 - x181*x69 - x64*x88 - x66*x98 - x68*x99;
   x183 := (1.0/2.0)*iBar_yzy;
   x184 := (1.0/4.0)*iBar_xxy;
   x185 := (1.0/4.0)*iBar_yyy;
   x186 := (1.0/4.0)*iBar_zzy;
   x187 := 2.0*gBar_xyy;
   x188 := gBar_yy*iBar_xx;
   x189 := 4.0*gBar_yy;
   x190 := gBar_yy*iBar_yy;
   x191 := gBar_yy*iBar_zz;
   x192 := 2.0*gBar_yzy;
   x193 := gBar_xyy*iBar_xx;
   x194 := gBar_xyy*x123;
   x195 := gBar_yyx*x123;
   x196 := gBar_yyx*iBar_xx;
   x197 := gBar_yzx*gBar_yzy;
   x198 := gBar_yyz*gBar_yzy;
   x199 := 24.0*gBar_yy;
   x200 := phi_x*x199;
   x201 := (1.0/2.0)*gBar_yyx;
   x202 := (1.0/2.0)*gBar_yyy;
   x203 := (1.0/2.0)*gBar_yyz;
   x204 := (gBar_xyy ** 2);
   x205 := (gBar_yyx ** 2);
   x206 := (gBar_yyz ** 2);
   x207 := (gBar_yzx ** 2);
   x208 := (gBar_yzy ** 2);
   x209 := 2.0*gBar_yy;
   x210 := (1.0/2.0)*gBar_yzy;
   x211 := (1.0/2.0)*gBar_yz;
   x212 := (1.0/2.0)*gBar_yzx;
   x213 := (1.0/2.0)*gBar_zzx;
   x214 := gBar_xyy*x81;
   x215 := gBar_xyz*x82;
   x216 := gBar_yyx*x81;
   x217 := gBar_yzx*x82;
   x218 := gBar_yyz*x83;
   x219 := gBar_yzy*x83;
   x220 := iBar_yz*x1;
   x221 := gBar_yz*iBar_xx;
   x222 := gBar_yz*iBar_yy;
   x223 := gBar_yz*iBar_zz;
   x224 := 4.0*gBar_yz;
   x225 := 2.0*gBar_yz;
   x226 := (1.0/2.0)*x166;
   x227 := gBar_xyy*x73;
   x228 := gBar_xyy*x220;
   x229 := iBar_xy*x96;
   x230 := x166*x96;
   x231 := gBar_xyy*x158;
   x232 := gBar_xyz*x75;
   x233 := iBar_xz*x97;
   x234 := iBar_xy*x98;
   x235 := x2*x60;
   x236 := iBar_xz*x99;
   x237 := gBar_xzz*x108;
   x238 := gBar_yyx*x73;
   x239 := gBar_yyx*x158;
   x240 := gBar_yyx*x220;
   x241 := gBar_yyz*x78;
   x242 := iBar_yz*x174;
   x243 := iBar_yz*x101;
   x244 := gBar_yzx*x75;
   x245 := gBar_yzx*x108;
   x246 := gBar_zzx*x108;
   x247 := gBar_yzy*x78;
   x248 := 24.0*gBar_yz;
   x249 := phi_x*x248;
   x250 := Gi_xy*x94 + Gi_xz*x90 + Gi_yy*x211 + (1.0/2.0)*Gi_yz*gBar_yy + (1.0/2.0)*Gi_zy*gBar_zz + Gi_zz*x211 + gBar_xyz*x10 + gBar_xyz*x11 + gBar_xyz*x9 + gBar_xzy*x10 + gBar_xzy*x11 - gBar_xzy*x214 + gBar_xzy*x216 + gBar_xzy*x227 - gBar_xzy*x238 + gBar_xzy*x9 - gBar_xzz*x215 
         + gBar_xzz*x217 + gBar_xzz*x228 - gBar_xzz*x230 + gBar_xzz*x232 - gBar_xzz*x240 - gBar_xzz*x244 + gBar_yyz*gBar_yzx*x158 + gBar_yyz*x22 + gBar_yyz*x23 - gBar_yyz*x235 + gBar_yyz*x237 + gBar_yyz*x24 - gBar_yyz*x246 - gBar_yzx*x10 - gBar_yzx*x11 - gBar_yzx*x151 
         - gBar_yzx*x168 + gBar_yzx*x214 - gBar_yzx*x216 - gBar_yzx*x227 + gBar_yzx*x238 - gBar_yzx*x9 - gBar_yzxx*x1 - gBar_yzxy*iBar_xy - gBar_yzxz*iBar_xz + gBar_yzy*x235 - gBar_yzy*x237 + gBar_yzy*x246 - gBar_yzyy*x2 - gBar_yzyz*iBar_yz + gBar_yzz*x172 - gBar_yzz*x218 
         + gBar_yzz*x219 - gBar_yzz*x231 + gBar_yzz*x239 + gBar_yzz*x241 - gBar_yzz*x245 - gBar_yzz*x247 - gBar_yzzz*x3 - gBar_zzx*x166*x201 + gBar_zzx*x215 - gBar_zzx*x217 - gBar_zzx*x228 + gBar_zzx*x230 - gBar_zzx*x232 + gBar_zzx*x240 + gBar_zzx*x244 - gBar_zzy*x172 
         - gBar_zzy*x183 + gBar_zzy*x218 - gBar_zzy*x219 + gBar_zzy*x231 - gBar_zzy*x239 - gBar_zzy*x241 + gBar_zzy*x245 + gBar_zzy*x247 + gBar_zzy*x25 + gBar_zzy*x26 + gBar_zzy*x27 - iBar_xxy*x88 - iBar_xxz*x4 + iBar_xy*x131*x212 + iBar_xy*x170*x201 - iBar_xyy*x212 - iBar_xyy*x98 
         - iBar_xyz*x201 - iBar_xz*x170*x212 - iBar_xzy*x213 - iBar_xzz*x212 - iBar_xzz*x97 - iBar_yyy*x210 - iBar_yzz*x203 - iBar_zzz*x101 + 12.0*phi_y*phi_z - 2.0*phi_yz - x0*x221 - x10*x249 - x101*x68 - x11*x249 + x119*x234 - x119*x236 - x12*x221 + x121*x243 + x122*x97 
         + x122*x98 + x127*x236 - x127*x243 - x131*x234 + x131*x236 - x15*x224 - x158*x197 - x16*x224 + x165*x229 - x165*x233 - x17*x222 - x170*x229 + x170*x233 - x177*x203 - x19*x224 - x20*x223 + x203*x242 + x207*x220 - x207*x226 - x210*x242 - x210*x66 - x212*x64 
         + x220*x49 - x222*x70 - x223*x71 - x225*x85 - x225*x86 - x225*x87 - x226*x49 - x248*x52;
   x251 := (1.0/2.0)*gBar_zzz;
   x252 := (1.0/4.0)*iBar_xxz;
   x253 := (1.0/4.0)*iBar_yyz;
   x254 := (1.0/4.0)*iBar_zzz;
   x255 := 2.0*gBar_xzz;
   x256 := 2.0*gBar_yzz;
   x257 := gBar_zz*iBar_xx;
   x258 := 4.0*gBar_zz;
   x259 := gBar_zz*iBar_yy;
   x260 := gBar_zz*iBar_zz;
   x261 := iBar_xx*x39;
   x262 := iBar_yy*x60;
   x263 := gBar_xzz*gBar_yzz;
   x264 := iBar_yy*x121;
   x265 := iBar_xx*x176;
   x266 := gBar_yzz*gBar_zzy;
   x267 := 24.0*gBar_zz;
   x268 := phi_x*x267;
   x269 := (gBar_xzz ** 2);
   x270 := (gBar_yzz ** 2);
   x271 := (gBar_zzx ** 2);
   x272 := (gBar_zzy ** 2);
   x273 := 2.0*gBar_zz;
   Rab (xx) := Gi_xx*gBar_xx + Gi_yx*gBar_xy + Gi_zx*gBar_xz - 3.0/4.0*gBar_xxx*iBar_xxx + gBar_xxx*x10 + gBar_xxx*x11 + gBar_xxx*x9 - gBar_xxxx*x1 - gBar_xxxy*iBar_xy - gBar_xxxz*iBar_xz - gBar_xxy*iBar_xyx - gBar_xxy*x22 - gBar_xxy*x23 - gBar_xxy*x24 - gBar_xxyy*x2 - gBar_xxyz*iBar_yz 
               - gBar_xxz*iBar_xy*x33 - gBar_xxz*iBar_xzx - gBar_xxz*x25 - gBar_xxz*x26 - gBar_xxz*x27 + gBar_xxz*x31 - gBar_xxzz*x3 - gBar_xyy*iBar_yyx - gBar_xyz*iBar_yzx - gBar_xyz*x35 - gBar_xzx*x31 - gBar_xzx*x5 - gBar_xzx*x61 - gBar_xzy*iBar_yzx + gBar_xzy*iBar_zz*x34 + gBar_xzy*x35 
               - gBar_xzz*iBar_zzx + gBar_yyx*x6 + gBar_yzx*x7 + gBar_zzx*x8 - iBar_xyx*x4 - iBar_xz*x63 - x0*x13 - x0 - x10*x51 - x11*x51 - x12*x13 + x12 - x14*x15 - x14*x16 - x14*x19 - x17*x18 - x18*x70 - x20*x21 - x21*x71 + x22*x28 + x23*x28 + x24*x28 + x25*x29 + x26*x29 
               + x27*x29 + x30*x32 - x30*x54 + x32*x38 - x32*x58 + x33*x34 - x34*x59 + x36*x37 + x36*x39 - x36*x56 + x37*x39 - x38*x54 + x40*x41 + x40*x42 - x41*x60 + x42*x43 - x43*x55 + x44*x45 - x45*x53 + x46*x47 - x47*x57 + x48*x49 - x49*x62 - x50*x52 - x64*x65 
               - x66*x67 - x68*x69 + x72*x73 - x72*x81 + x73*x76 + x74*x75 - x74*x82 + x75*x79 - x76*x81 + x77*x78 - x77*x83 + x78*x80 - x79*x82 - x80*x83 - x84*x85 - x84*x86 - x84*x87;
   Rab (xy) := gBar_xxy*x89 + gBar_xzy*x5 - gBar_yyy*x6 + gBar_zzy*x8 - iBar_xxy*x65 - iBar_xyy*x4 - iBar_xzy*x88 + x153;
   Rab (xz) := gBar_xxz*x89 + gBar_yyz*x6 - gBar_zzz*x8 - iBar_xxz*x65 + iBar_xyx*x97 - iBar_xyz*x4 - iBar_xzz*x88 + x182;
   Rab (xy) := -gBar_xxx*x184 + gBar_yyx*x185 - gBar_yyy*x154 + gBar_yzx*x183 - gBar_yzy*x7 + gBar_zzx*x186 - iBar_xyx*x96 + x153;
   Rab (yy) := Gi_xy*gBar_xy + Gi_yy*gBar_yy + Gi_zy*gBar_yz + gBar_xxy*x184 - gBar_xyx*iBar_xxy - gBar_xyy*gBar_yyx*x53 + gBar_xyy*x102 - gBar_xyy*x132 - gBar_xyz*gBar_yzx*x57 - gBar_xyz*iBar_xzy + gBar_xyz*x103 - gBar_yyx*iBar_xyy - gBar_yyx*x10 - gBar_yyx*x11 + gBar_yyx*x132 - gBar_yyx*x9 
               - gBar_yyxx*x1 - gBar_yyxy*iBar_xy - gBar_yyxz*iBar_xz - 3.0/4.0*gBar_yyy*iBar_yyy + gBar_yyy*x22 + gBar_yyy*x23 + gBar_yyy*x24 - gBar_yyyy*x2 - gBar_yyyz*iBar_yz - gBar_yyz*iBar_yzy - gBar_yyz*x194 + gBar_yyz*x195 - gBar_yyz*x25 - gBar_yyz*x26 - gBar_yyz*x27 + gBar_yyz*x61 
               - gBar_yyzz*x3 - gBar_yzx*iBar_xzy - gBar_yzx*x130 - gBar_yzy*x183 + gBar_yzy*x194 - gBar_yzy*x195 - gBar_yzy*x61 - gBar_yzz*iBar_zzy + gBar_zzy*x186 - iBar_xyy*x96 + iBar_xzy*x98 - x0*x188 + x10*x187 - x10*x200 + x11*x187 - x11*x200 + x119*x121 - x119*x127 
               + x119*x150 - x119*x40 - x12*x188 - x121*x127 - x121*x131 + x121*x150 + x127*x131 + x129*x197 - x131*x150 + x131*x40 - x15*x189 - x16*x189 - x17*x190 - x17 - x176*x193 + x176*x196 + x187*x9 - x189*x19 - x190*x70 - x191*x20 - x191*x71 + x192*x25 + x192*x26 
               + x192*x27 + x193*x56 - x196*x56 + x198*x48 - x198*x62 - x199*x52 - x201*x64 - x202*x66 - x203*x68 + x204*x73 - x204*x81 + x205*x73 - x205*x81 + x206*x78 - x206*x83 + x207*x75 - x207*x82 + x208*x78 - x208*x83 - x209*x85 - x209*x86 - x209*x87 + x70 
               + x75*x77 - x77*x82;
   Rab (yz) := gBar_xxz*x184 + gBar_yyz*x185 - gBar_zzz*x186 + iBar_xyy*x97 - iBar_xyz*x96 - iBar_yyz*x202 - iBar_yzz*x210 + x250;
   Rab (xz) := -gBar_xxx*x252 - gBar_xzz*x5 + gBar_yyx*x253 - gBar_yzz*x7 + gBar_zzx*x254 + iBar_yzz*x212 - iBar_zzx*x251 + x182;
   Rab (yz) := gBar_xxy*x252 - gBar_yyy*x253 + gBar_zzy*x254 - iBar_xzy*x99 + iBar_xzz*x98 - iBar_yzy*x101 - iBar_zzy*x251 + x250;
   Rab (zz) := Gi_xz*gBar_xz + Gi_yz*gBar_yz + Gi_zz*gBar_zz + gBar_xxz*x252 - gBar_xzx*iBar_xxz - gBar_xzy*gBar_yzx*x53 - gBar_xzy*iBar_xyz + gBar_xzy*x155 - gBar_xzz*gBar_zzx*x57 + gBar_xzz*x122 + gBar_xzz*x156 - gBar_xzz*x181 + gBar_xzz*x261 - gBar_xzz*x265 + gBar_yyz*x253 
               - gBar_yzx*iBar_xyz - gBar_yzy*iBar_yyz + gBar_yzz*x152 - gBar_yzz*x177 - gBar_yzz*x262 + gBar_yzz*x264 - gBar_zzx*iBar_xzz - gBar_zzx*x10 - gBar_zzx*x11 - gBar_zzx*x122 - gBar_zzx*x169 + gBar_zzx*x181 - gBar_zzx*x261 + gBar_zzx*x265 - gBar_zzx*x9 - gBar_zzxx*x1 
               - gBar_zzxy*iBar_xy - gBar_zzxz*iBar_xz - gBar_zzy*iBar_yzz - gBar_zzy*x152 + gBar_zzy*x177 - gBar_zzy*x22 - gBar_zzy*x23 - gBar_zzy*x24 + gBar_zzy*x262 - gBar_zzy*x264 - 1.0/2.0*gBar_zzy*x66 - gBar_zzyy*x2 - gBar_zzyz*iBar_yz - 3.0/4.0*gBar_zzz*iBar_zzz + gBar_zzz*x25 
               + gBar_zzz*x26 + gBar_zzz*x27 - gBar_zzzz*x3 + iBar_xyz*x97 - iBar_xz*iBar_yz*x263 - iBar_xzz*x99 - iBar_yzz*x101 - x0*x257 + x10*x255 - x10*x268 + x11*x255 - x11*x268 - x12*x257 + x129*x263 - x15*x258 - x16*x258 + x165*x174 - x17*x259 - x170*x174 + x170*x175 
               + x174*x54 - x175*x54 - x19*x258 - x20*x260 - x20 + x207*x73 - x207*x81 - x213*x64 + x22*x256 + x23*x256 + x24*x256 - x251*x68 + x255*x9 - x259*x70 - x260*x71 + x266*x48 - x266*x62 - x267*x52 + x269*x75 - x269*x82 + x270*x78 - x270*x83 + x271*x75 
               - x271*x82 + x272*x78 - x272*x83 - x273*x85 - x273*x86 - x273*x87 + x71 + x73*x80 - x80*x81;
end set_3d_ricci;
-- end: ./cadabra/ricci.ad -------------------------------------------------------------------------
-- beg: ./cadabra/ricci-scalar.ad ------------------------------------------------------------------
Procedure set_3d_ricci_scalar is
   x0,  x1,  x2,  x3,  x4,  x5,  x6,  x7,  x8,  x9,  x10, x11, x12, x13, x14, x15, x16, 
   x17, x18, x19, x20, x21, x22, x23, x24, x25, x26, x27, x28, x29, x30, x31, x32, x33, 
   x34, x35, x36, x37, x38, x39, x40, x41, x42, x43, x44, x45, x46, x47, x48, x49, x50, 
   x51, x52, x53 : Real;
begin
   x0  := (1.0/4.0)*gBar_xxx;
   x1  := (1.0/2.0)*gBar_xxy;
   x2  := iBar_xxx*iBar_xy;
   x3  := (1.0/4.0)*gBar_xxy;
   x4  := iBar_xxy*iBar_yy;
   x5  := iBar_xxz*iBar_yz;
   x6  := (1.0/2.0)*gBar_xxz;
   x7  := iBar_xxx*iBar_xz;
   x8  := (1.0/4.0)*gBar_xxz;
   x9  := iBar_xxy*iBar_yz;
   x10 := iBar_xxz*iBar_zz;
   x11 := (1.0/2.0)*gBar_xyx;
   x12 := (1.0/2.0)*gBar_xyy;
   x13 := iBar_xx*iBar_yyx;
   x14 := iBar_xy*iBar_yyy;
   x15 := iBar_xz*iBar_yyz;
   x16 := (1.0/2.0)*gBar_xyz;
   x17 := iBar_xx*iBar_yzx;
   x18 := iBar_xy*iBar_xzx;
   x19 := iBar_xy*iBar_yzy;
   x20 := iBar_xz*x16;
   x21 := iBar_yz*x16;
   x22 := iBar_xyz*iBar_zz;
   x23 := iBar_xzy*iBar_yy;
   x24 := (1.0/2.0)*gBar_xzx;
   x25 := (1.0/2.0)*gBar_xzy;
   x26 := iBar_xyx*iBar_xz;
   x27 := iBar_yz*x25;
   x28 := iBar_xz*iBar_yzz;
   x29 := (1.0/2.0)*gBar_xzz;
   x30 := iBar_xx*iBar_zzx;
   x31 := iBar_xy*iBar_zzy;
   x32 := iBar_xz*iBar_zzz;
   x33 := (1.0/4.0)*gBar_yyx;
   x34 := (1.0/2.0)*gBar_yyx;
   x35 := (1.0/4.0)*gBar_yyy;
   x36 := (1.0/2.0)*gBar_yyz;
   x37 := iBar_xz*iBar_yyx;
   x38 := (1.0/4.0)*gBar_yyz;
   x39 := iBar_yyy*iBar_yz;
   x40 := iBar_yyz*iBar_zz;
   x41 := (1.0/2.0)*gBar_yzx;
   x42 := iBar_yz*x41;
   x43 := (1.0/2.0)*gBar_yzy;
   x44 := (1.0/2.0)*gBar_yzz;
   x45 := iBar_xy*iBar_zzx;
   x46 := iBar_yy*iBar_zzy;
   x47 := iBar_yz*iBar_zzz;
   x48 := (1.0/4.0)*gBar_zzx;
   x49 := (1.0/2.0)*gBar_zzx;
   x50 := (1.0/4.0)*gBar_zzy;
   x51 := (1.0/2.0)*gBar_zzy;
   x52 := (1.0/4.0)*gBar_zzz;
   x53 := 48.0*phi_x;
   R := (8.0*Gi_x*phi_x + Gi_xx + 8.0*Gi_y*phi_y + Gi_yy + 8.0*Gi_z*phi_z + Gi_zz - iBar_xx*iBar_xxx*x0 - iBar_xx*iBar_xyx*x1 - iBar_xx*iBar_xzx*x6 - 24.0*iBar_xx*(phi_x ** 2) - 8.0*iBar_xx*phi_xx - iBar_xxy*iBar_xy*x0 - iBar_xxz*iBar_xz*x0 - iBar_xy*iBar_xyx*x34 - iBar_xy*iBar_xyy*x1 
      - iBar_xy*iBar_xzy*x6 - iBar_xy*iBar_yyx*x35 - iBar_xy*iBar_yzx*x36 - 16.0*iBar_xy*phi_xy - iBar_xy*phi_y*x53 + iBar_xyx*x20 - iBar_xyy*iBar_yy*x34 + iBar_xyy*x21 - iBar_xyy*x27 - iBar_xyy*x42 - iBar_xyz*iBar_xz*x1 - iBar_xyz*iBar_yz*x34 - iBar_xz*iBar_xzx*x49 
      - iBar_xz*iBar_xzz*x6 - iBar_xz*iBar_yzx*x51 - iBar_xz*iBar_zzx*x52 - 16.0*iBar_xz*phi_xz - iBar_xz*phi_z*x53 - iBar_xzy*iBar_yz*x49 - iBar_xzz*iBar_zz*x49 - iBar_xzz*x21 + iBar_xzz*x27 - iBar_xzz*x42 - iBar_yy*iBar_yyy*x35 - iBar_yy*iBar_yzy*x36 - 24.0*iBar_yy*(phi_y ** 2) 
      - 8.0*iBar_yy*phi_yy - iBar_yyz*iBar_yz*x35 - iBar_yz*iBar_yzy*x51 - iBar_yz*iBar_yzz*x36 - iBar_yz*iBar_zzy*x52 - 48.0*iBar_yz*phi_y*phi_z - 16.0*iBar_yz*phi_yz - iBar_yzz*iBar_zz*x51 - iBar_yzz*x20 - iBar_zz*iBar_zzz*x52 - 24.0*iBar_zz*(phi_z ** 2) - 8.0*iBar_zz*phi_zz - x10*x24 
      + x10*x8 - x11*x2 - x11*x4 - x11*x5 - x12*x13 - x12*x14 - x12*x15 + x13*x33 + x14*x33 + x15*x33 - x16*x17 - x16*x18 - x16*x19 + x16*x22 - x16*x23 - x17*x25 + x17*x41 + x18*x25 - x18*x41 - x19*x25 + x19*x41 + x2*x3 - x22*x25 - x22*x41 + x23*x25 - x23*x41 
      - x24*x7 - x24*x9 - x25*x26 - x25*x28 - x26*x41 + x28*x41 - x29*x30 - x29*x31 - x29*x32 + x3*x4 + x3*x5 + x30*x48 + x31*x48 + x32*x48 + x37*x38 - x37*x43 + x38*x39 + x38*x40 - x39*x43 - x40*x43 - x44*x45 - x44*x46 - x44*x47 + x45*x50 + x46*x50 + x47*x50 
      + x7*x8 + x8*x9)*exp(-4.0*phi);
end set_3d_ricci_scalar;
-- end: ./cadabra/ricci-scalar.ad ------------------------------------------------------------------

-- beg: ./cadabra/hamiltonian.ad -------------------------------------------------------------------
Procedure set_hamiltonian is
begin
   Ham := -ABar_xx*BBar_xx - 2.0*ABar_xy*BBar_xy - 2.0*ABar_xz*BBar_xz - ABar_yy*BBar_yy - 2.0*ABar_yz*BBar_yz - ABar_zz*BBar_zz + R + (2.0/3.0)*(trK ** 2);
end set_hamiltonian;
-- end: ./cadabra/hamiltonian.ad -------------------------------------------------------------------
-- beg: ./cadabra/momentum.ad ----------------------------------------------------------------------
Procedure set_momentum is
   x0,  x1,  x2,  x3,  x4,  x5,  x6,  x7,  x8,  x9,  x10, x11, x12, x13, x14, x15, x16, 
   x17, x18, x19, x20, x21, x22, x23, x24, x25, x26, x27, x28, x29, x30, x31, x32, x33, 
   x34, x35, x36, x37, x38, x39, x40, x41, x42, x43, x44, x45, x46, x47, x48, x49, x50, 
   x51, x52, x53, x54, x55, x56, x57, x58, x59, x60, x61, x62, x63, x64, x65, x66, x67, 
   x68, x69, x70, x71, x72, x73, x74, x75, x76, x77, x78, x79, x80, x81, x82, x83 : Real;
begin
   x0  := 6.0*phi_x;
   x1  := 6.0*phi_y;
   x2  := 6.0*phi_z;
   x3  := (2.0/3.0)*trK_x;
   x4  := (2.0/3.0)*trK_y;
   x5  := (2.0/3.0)*trK_z;
   x6  := ABar_xx*iBar_xx;
   x7  := ABar_xx*iBar_xy;
   x8  := ABar_xx*iBar_xz;
   x9  := iBar_xx*iBar_xy;
   x10 := ABar_xxz*iBar_xz;
   x11 := ABar_xy*iBar_xx;
   x12 := ABar_xy*iBar_xy;
   x13 := ABar_xy*iBar_yy;
   x14 := ABar_xy*iBar_yz;
   x15 := ABar_xy*iBar_xz;
   x16 := iBar_xx*iBar_yy;
   x17 := iBar_xx*iBar_yz;
   x18 := iBar_xy*iBar_xz;
   x19 := ABar_xz*iBar_xx;
   x20 := ABar_xz*iBar_xz;
   x21 := ABar_xz*iBar_yz;
   x22 := ABar_xz*iBar_zz;
   x23 := ABar_xz*iBar_xy;
   x24 := ABar_xzz*iBar_zz;
   x25 := ABar_yy*iBar_xy;
   x26 := ABar_yy*iBar_yy;
   x27 := ABar_yy*iBar_yz;
   x28 := iBar_xy*iBar_yy;
   x29 := iBar_xy*iBar_yz;
   x30 := ABar_yz*iBar_xy;
   x31 := ABar_yz*iBar_xz;
   x32 := ABar_yz*iBar_yz;
   x33 := ABar_yz*iBar_zz;
   x34 := ABar_yz*iBar_yy;
   x35 := iBar_xz*iBar_yy;
   x36 := ABar_yzz*iBar_zz;
   x37 := iBar_xz*iBar_yz;
   x38 := ABar_zz*iBar_xz;
   x39 := ABar_zz*iBar_yz;
   x40 := ABar_zz*iBar_zz;
   x41 := ABar_zzz*iBar_zz;
   x42 := BBar_xx*gBar_xyx;
   x43 := BBar_xx*gBar_xzx;
   x44 := BBar_xy*gBar_xxy;
   x45 := BBar_xy*iBar_xz;
   x46 := BBar_xy*gBar_yyx;
   x47 := BBar_xz*gBar_xxz;
   x48 := BBar_xz*iBar_xy;
   x49 := BBar_xz*gBar_zzx;
   x50 := BBar_yy*gBar_xyy;
   x51 := BBar_yy*gBar_yzy;
   x52 := BBar_yz*iBar_xx;
   x53 := BBar_yz*iBar_xy;
   x54 := BBar_yz*gBar_zzy;
   x55 := BBar_zz*gBar_xzz;
   x56 := BBar_zz*gBar_yzz;
   x57 := (iBar_xy ** 2);
   x58 := (iBar_xz ** 2);
   x59 := iBar_xx*iBar_xz;
   x60 := (1.0/2.0)*BBar_xx;
   x61 := gBar_xxx*x60;
   x62 := gBar_xxy*x60;
   x63 := gBar_xxz*x60;
   x64 := (1.0/2.0)*BBar_yy;
   x65 := gBar_yyx*x64;
   x66 := gBar_yyy*x64;
   x67 := gBar_yyz*x64;
   x68 := (1.0/2.0)*BBar_zz;
   x69 := gBar_zzx*x68;
   x70 := gBar_zzy*x68;
   x71 := gBar_zzz*x68;
   x72 := iBar_xxx + iBar_xyy + iBar_xzz;
   x73 := iBar_xyx + iBar_yyy + iBar_yzz;
   x74 := iBar_xzx + iBar_yzy + iBar_zzz;
   x75 := iBar_yy*iBar_yz;
   x76 := BBar_xy*iBar_yz;
   x77 := BBar_xz*iBar_yy;
   x78 := BBar_yz*gBar_yyz;
   x79 := (iBar_yz ** 2);
   x80 := iBar_xy*iBar_zz;
   x81 := BBar_xy*iBar_zz;
   x82 := BBar_xz*iBar_yz;
   x83 := BBar_yz*iBar_xz;
   Mom (1) := ABar_xxx*(iBar_xx ** 2) + ABar_xxy*x9 + 2.0*ABar_xyx*x9 + ABar_xyy*x16 + ABar_xyy*x57 + ABar_xyz*x17 + ABar_xyz*x18 + 2.0*ABar_xzx*x59 + ABar_xzy*x17 + ABar_xzy*x18 + ABar_xzz*x58 + ABar_yyx*x57 + ABar_yyy*x28 + ABar_yyz*x29 + 2.0*ABar_yzx*x18 + ABar_yzy*x29 + ABar_yzy*x35 
            + ABar_yzz*x37 + ABar_zzx*x58 + ABar_zzy*x37 + BBar_xx*x0 + BBar_xy*x1 + BBar_xz*x2 - gBar_xyz*x45 + gBar_xyz*x48 + gBar_xyz*x52 + gBar_xzy*x45 - gBar_xzy*x48 + gBar_xzy*x52 + gBar_yyz*x53 + gBar_yzx*x45 + gBar_yzx*x48 - gBar_yzx*x52 + iBar_xx*x10 + iBar_xx*x24 - iBar_xx*x3 
            + iBar_xx*x44 + iBar_xx*x47 + iBar_xx*x50 + iBar_xx*x55 + iBar_xx*x61 - iBar_xx*x65 - iBar_xx*x69 + iBar_xxx*x12 + iBar_xxx*x20 + iBar_xxx*x6 + iBar_xxy*x13 + iBar_xxy*x21 + iBar_xxy*x7 + iBar_xxz*x14 + iBar_xxz*x22 + iBar_xxz*x8 + iBar_xy*x36 - iBar_xy*x4 + iBar_xy*x42 
            + iBar_xy*x46 + iBar_xy*x56 - iBar_xy*x62 + iBar_xy*x66 - iBar_xy*x70 + iBar_xyx*x11 + iBar_xyx*x25 + iBar_xyx*x31 + iBar_xyy*x12 + iBar_xyy*x26 + iBar_xyy*x32 + iBar_xyz*x15 + iBar_xyz*x27 + iBar_xyz*x33 + iBar_xz*x41 + iBar_xz*x43 + iBar_xz*x49 - iBar_xz*x5 + iBar_xz*x51 
            + iBar_xz*x54 - iBar_xz*x63 - iBar_xz*x67 + iBar_xz*x71 + iBar_xzx*x19 + iBar_xzx*x30 + iBar_xzx*x38 + iBar_xzy*x23 + iBar_xzy*x34 + iBar_xzy*x39 + iBar_xzz*x20 + iBar_xzz*x32 + iBar_xzz*x40 + x11*x73 + x12*x72 + x19*x74 + x20*x72 + x25*x73 + x30*x74 + x31*x73 
            + x38*x74 + x6*x72;
   Mom (2) := ABar_xxx*x9 + ABar_xxy*x57 + ABar_xyx*x16 + ABar_xyx*x57 + 2.0*ABar_xyy*x28 + ABar_xyz*x29 + ABar_xyz*x35 + ABar_xzx*x17 + ABar_xzx*x18 + 2.0*ABar_xzy*x29 + ABar_xzz*x37 + ABar_yyx*x28 + ABar_yyy*(iBar_yy ** 2) + ABar_yyz*x75 + ABar_yzx*x29 + ABar_yzx*x35 + 2.0*ABar_yzy*x75 
            + ABar_yzz*x79 + ABar_zzx*x37 + ABar_zzy*x79 + BBar_xy*x0 + BBar_yy*x1 + BBar_yz*x2 + gBar_xyz*x53 - gBar_xyz*x76 + gBar_xyz*x77 + gBar_xzy*x53 + gBar_xzy*x76 - gBar_xzy*x77 - gBar_yzx*x53 + gBar_yzx*x76 + gBar_yzx*x77 + iBar_xy*x10 + iBar_xy*x24 - iBar_xy*x3 + iBar_xy*x44 
            + iBar_xy*x47 + iBar_xy*x50 + iBar_xy*x55 + iBar_xy*x61 - iBar_xy*x65 - iBar_xy*x69 + iBar_xyx*x12 + iBar_xyx*x20 + iBar_xyx*x6 + iBar_xyy*x13 + iBar_xyy*x21 + iBar_xyy*x7 + iBar_xyz*x14 + iBar_xyz*x22 + iBar_xyz*x8 + iBar_yy*x36 - iBar_yy*x4 + iBar_yy*x42 + iBar_yy*x46 
            + iBar_yy*x56 - iBar_yy*x62 + iBar_yy*x66 - iBar_yy*x70 + iBar_yy*x78 + iBar_yyx*x11 + iBar_yyx*x25 + iBar_yyx*x31 + iBar_yyy*x12 + iBar_yyy*x26 + iBar_yyy*x32 + iBar_yyz*x15 + iBar_yyz*x27 + iBar_yyz*x33 + iBar_yz*x41 + iBar_yz*x43 + iBar_yz*x49 - iBar_yz*x5 + iBar_yz*x51 
            + iBar_yz*x54 - iBar_yz*x63 - iBar_yz*x67 + iBar_yz*x71 + iBar_yzx*x19 + iBar_yzx*x30 + iBar_yzx*x38 + iBar_yzy*x23 + iBar_yzy*x34 + iBar_yzy*x39 + iBar_yzz*x20 + iBar_yzz*x32 + iBar_yzz*x40 + x12*x73 + x13*x72 + x21*x72 + x23*x74 + x26*x73 + x32*x73 + x34*x74 
            + x39*x74 + x7*x72;
   Mom (3) := ABar_xxx*x59 + ABar_xxy*x18 + ABar_xxz*x58 + ABar_xyx*x17 + ABar_xyx*x18 + ABar_xyy*x29 + ABar_xyy*x35 + 2.0*ABar_xyz*x37 + ABar_xzx*iBar_xx*iBar_zz + ABar_xzx*x58 + ABar_xzy*x37 + ABar_xzy*x80 + ABar_yyx*x29 + ABar_yyy*x75 + ABar_yyz*x79 + ABar_yzx*x37 + ABar_yzx*x80 
            + ABar_yzy*iBar_yy*iBar_zz + ABar_yzy*x79 + ABar_zzx*iBar_xz*iBar_zz + ABar_zzy*iBar_yz*iBar_zz + ABar_zzz*(iBar_zz ** 2) + BBar_xz*x0 + BBar_yz*x1 + BBar_zz*x2 - gBar_xyz*x81 + gBar_xyz*x82 + gBar_xyz*x83 + gBar_xzy*x81 - gBar_xzy*x82 + gBar_xzy*x83 + gBar_yzx*x81 
            + gBar_yzx*x82 - gBar_yzx*x83 + 2.0*iBar_xz*x24 - iBar_xz*x3 + iBar_xz*x44 + iBar_xz*x47 + iBar_xz*x50 + iBar_xz*x55 + iBar_xz*x61 - iBar_xz*x65 - iBar_xz*x69 + iBar_xzx*x12 + iBar_xzx*x20 + iBar_xzx*x6 + iBar_xzy*x13 + iBar_xzy*x21 + iBar_xzy*x7 + iBar_xzz*x14 + iBar_xzz*x22 
            + iBar_xzz*x8 + 2.0*iBar_yz*x36 - iBar_yz*x4 + iBar_yz*x42 + iBar_yz*x46 + iBar_yz*x56 - iBar_yz*x62 + iBar_yz*x66 - iBar_yz*x70 + iBar_yz*x78 + iBar_yzx*x11 + iBar_yzx*x25 + iBar_yzx*x31 + iBar_yzy*x12 + iBar_yzy*x26 + iBar_yzy*x32 + iBar_yzz*x15 + iBar_yzz*x27 
            + iBar_yzz*x33 + iBar_zz*x43 + iBar_zz*x49 - iBar_zz*x5 + iBar_zz*x51 + iBar_zz*x54 - iBar_zz*x63 - iBar_zz*x67 + iBar_zz*x71 + iBar_zzx*x19 + iBar_zzx*x30 + iBar_zzx*x38 + iBar_zzy*x23 + iBar_zzy*x34 + iBar_zzy*x39 + iBar_zzz*x20 + iBar_zzz*x32 + iBar_zzz*x40 + x14*x72 
            + x15*x73 + x20*x74 + x22*x72 + x27*x73 + x32*x74 + x33*x73 + x40*x74 + x72*x8;
end set_momentum;
-- end: ./cadabra/momentum.ad ----------------------------------------------------------------------

      procedure set_data is
         det : Real;
         i, j, k : Integer;
         x, y, z : Real;
      begin

         i := point.i;
         j := point.j;
         k := point.k;

         x := point.x;
         y := point.y;
         z := point.z;

         Gi   := BSSNBase.Gi   (i,j,k);
         phi  := BSSNBase.phi  (i,j,k);
         trK  := BSSNBase.trK  (i,j,k);
         gBar := BSSNBase.gBar (i,j,k);
         ABar := BSSNBase.ABar (i,j,k);

         iBar := symm_inverse (gBar);
         BBar := symm_raise_indices (ABar, iBar);

         -- second order centred finite differences for the conformal factor phi

         declare
            phi : ConFactGridArray renames BSSNBase.phi;
         begin

            d1phi (1) := (phi (i+1,j,k) - phi (i-1,j,k)) / (two_dx);
            d1phi (2) := (phi (i,j+1,k) - phi (i,j-1,k)) / (two_dy);
            d1phi (3) := (phi (i,j,k+1) - phi (i,j,k-1)) / (two_dz);

            d2phi (xx) := (phi (i+1,j,k) - 2.0*phi (i,j,k) + phi (i-1,j,k)) / (dxdx);
            d2phi (yy) := (phi (i,j+1,k) - 2.0*phi (i,j,k) + phi (i,j-1,k)) / (dydy);
            d2phi (zz) := (phi (i,j,k+1) - 2.0*phi (i,j,k) + phi (i,j,k-1)) / (dzdz);

            d2phi (xy) := (phi (i+1,j+1,k) + phi (i-1,j-1,k) - phi (i+1,j-1,k) - phi (i-1,j+1,k)) / (four_dxdy);
            d2phi (xz) := (phi (i+1,j,k+1) + phi (i-1,j,k-1) - phi (i+1,j,k-1) - phi (i-1,j,k+1)) / (four_dxdz);
            d2phi (yz) := (phi (i,j+1,k+1) + phi (i,j-1,k-1) - phi (i,j+1,k-1) - phi (i,j-1,k+1)) / (four_dydz);

         end;

         -- second order centred finite differences for trK

         declare
            trK : TraceKGridArray renames BSSNBase.trK;
         begin

            d1trK (1) := (trK (i+1,j,k) - trK (i-1,j,k)) / (two_dx);
            d1trK (2) := (trK (i,j+1,k) - trK (i,j-1,k)) / (two_dy);
            d1trK (3) := (trK (i,j,k+1) - trK (i,j,k-1)) / (two_dz);

         end;

         -- second order centred finite differences for Gi

         declare
            Gi : GammaGridArray renames BSSNBase.Gi;
         begin

            d1Gi (1) := (Gi (i+1,j,k) - Gi (i-1,j,k)) / (two_dx);
            d1Gi (2) := (Gi (i,j+1,k) - Gi (i,j-1,k)) / (two_dy);
            d1Gi (3) := (Gi (i,j,k+1) - Gi (i,j,k-1)) / (two_dz);

         end;

         -- second order centred finite differences for the 3-metric

         declare
            gBar : MetricGridArray renames BSSNBase.gBar;
         begin

            d1gBar (1) := (gBar (i+1,j,k) - gBar (i-1,j,k)) / (two_dx);
            d1gBar (2) := (gBar (i,j+1,k) - gBar (i,j-1,k)) / (two_dy);
            d1gBar (3) := (gBar (i,j,k+1) - gBar (i,j,k-1)) / (two_dz);

            d2gBar (xx) := (gBar (i+1,j,k) - 2.0*gBar (i,j,k) + gBar (i-1,j,k)) / (dxdx);
            d2gBar (yy) := (gBar (i,j+1,k) - 2.0*gBar (i,j,k) + gBar (i,j-1,k)) / (dydy);
            d2gBar (zz) := (gBar (i,j,k+1) - 2.0*gBar (i,j,k) + gBar (i,j,k-1)) / (dzdz);

            d2gBar (xy) := (gBar (i+1,j+1,k) + gBar (i-1,j-1,k) - gBar (i+1,j-1,k) - gBar (i-1,j+1,k)) / (four_dxdy);
            d2gBar (xz) := (gBar (i+1,j,k+1) + gBar (i-1,j,k-1) - gBar (i+1,j,k-1) - gBar (i-1,j,k+1)) / (four_dxdz);
            d2gBar (yz) := (gBar (i,j+1,k+1) + gBar (i,j-1,k-1) - gBar (i,j+1,k-1) - gBar (i,j-1,k+1)) / (four_dydz);

         end;

         -- second order centred finite differences for the ABar_{ab}

         declare
            ABar : ExtcurvGridArray renames BSSNBase.ABar;
         begin

            d1ABar (1) := (ABar (i+1,j,k) - ABar (i-1,j,k)) / (two_dx);
            d1ABar (2) := (ABar (i,j+1,k) - ABar (i,j-1,k)) / (two_dy);
            d1ABar (3) := (ABar (i,j,k+1) - ABar (i,j,k-1)) / (two_dz);

         end;

         d1iBar (1) := - symm_raise_indices (d1gBar (1), iBar);
         d1iBar (2) := - symm_raise_indices (d1gBar (2), iBar);
         d1iBar (3) := - symm_raise_indices (d1gBar (3), iBar);

         set_3d_ricci;

         set_3d_ricci_scalar;

      end set_data;

   begin

      set_data;

      set_hamiltonian;
      set_momentum;

      declare
         i, j, k : Integer;
      begin

         i := point.i;
         j := point.j;
         k := point.k;

         BSSNBase.Ham (i,j,k) := Ham;
         BSSNBase.Mom (i,j,k) := Mom;

      end;

   end set_constraints;

   function get_trABar (i, j, k : Integer) return Real is

      ABar : ExtcurvPointArray;
      gBar : MetricPointArray;
      iBar : MetricPointArray;

   begin

      gBar := BSSNBase.gBar (i,j,k);
      ABar := BSSNBase.ABar (i,j,k);

      iBar := symm_inverse (gBar);

      return symm_trace (ABar,iBar);

   end get_trABar;

   function get_trABar (point : GridPoint) return Real is
      i, j, k : Integer;
   begin

      i := point.i;
      j := point.j;
      k := point.k;

      return get_trABar (i, j, k);

   end get_trABar;

   function get_detg (i, j, k : Integer) return Real is
   begin

      return symm_det (BSSNBase.gBar (i,j,k));

   end get_detg;

   function get_detg (point : GridPoint) return Real is
      i, j, k : Integer;
   begin

      i := point.i;
      j := point.j;
      k := point.k;

      return get_detg (i, j, k);

   end get_detg;

   procedure set_finite_diff_factors is
   begin

      dxdx := dx * dx;
      dydy := dy * dy;
      dzdz := dz * dz;

      two_dx := 2.0 * dx;
      two_dy := 2.0 * dy;
      two_dz := 2.0 * dz;

      four_dxdy := 4.0 * dx * dy;
      four_dxdz := 4.0 * dx * dz;
      four_dydz := 4.0 * dy * dz;

   end set_finite_diff_factors;

   procedure set_constraints_intr is

      b : Integer;

   begin

      for a in 1 .. interior_num loop

         b := interior (a);

         set_constraints (grid_point_list(b));

      end loop;

   end set_constraints_intr;

   procedure set_constraints_bndry_ns is

      b, i, j, k : Integer;

   begin

      -- apply periodic boundary conditions

      -- north/south boundaries

      for a in 1 .. north_bndry_num loop

         b := north_bndry (a);

         i := grid_point_list (b).i;
         j := grid_point_list (b).j;
         k := grid_point_list (b).k;  -- equals num_z

         BSSNBase.Ham (i,j,k) := BSSNBase.Ham (i,j,2);
         BSSNBase.Mom (i,j,k) := BSSNBase.Mom (i,j,2);

      end loop;

      for a in 1 .. south_bndry_num loop

         b := south_bndry (a);

         i := grid_point_list (b).i;
         j := grid_point_list (b).j;
         k := grid_point_list (b).k;  -- equals 1

         BSSNBase.Ham (i,j,k) := BSSNBase.Ham (i,j,num_z-1);
         BSSNBase.Mom (i,j,k) := BSSNBase.Mom (i,j,num_z-1);

      end loop;

   end set_constraints_bndry_ns;

   procedure set_constraints_bndry_ew is

      b, i, j, k : Integer;

   begin

      -- apply periodic boundary conditions

      -- east/west boundaries

      for a in 1 .. east_bndry_num loop

         b := east_bndry (a);

         i := grid_point_list (b).i;
         j := grid_point_list (b).j;  -- equals num_y
         k := grid_point_list (b).k;

         BSSNBase.Ham (i,j,k) := BSSNBase.Ham (i,2,k);
         BSSNBase.Mom (i,j,k) := BSSNBase.Mom (i,2,k);

      end loop;

      for a in 1 .. west_bndry_num loop

         b := west_bndry (a);

         i := grid_point_list (b).i;
         j := grid_point_list (b).j;  -- equals 1
         k := grid_point_list (b).k;

         BSSNBase.Ham (i,j,k) := BSSNBase.Ham (i,num_y-1,k);
         BSSNBase.Mom (i,j,k) := BSSNBase.Mom (i,num_y-1,k);

      end loop;

   end set_constraints_bndry_ew;

   procedure set_constraints_bndry_fb is

      b, i, j, k : Integer;

   begin

      -- apply periodic boundary conditions

      -- front/back boundaries

      for a in 1 .. front_bndry_num loop

         b := front_bndry (a);

         i := grid_point_list (b).i;  -- equals num_x
         j := grid_point_list (b).j;
         k := grid_point_list (b).k;

         BSSNBase.Ham (i,j,k) := BSSNBase.Ham (2,j,k);
         BSSNBase.Mom (i,j,k) := BSSNBase.Mom (2,j,k);

      end loop;

      for a in 1 .. back_bndry_num loop

         b := back_bndry (a);

         i := grid_point_list (b).i;  -- equals 1
         j := grid_point_list (b).j;
         k := grid_point_list (b).k;

         BSSNBase.Ham (i,j,k) := BSSNBase.Ham (num_x-1,j,k);
         BSSNBase.Mom (i,j,k) := BSSNBase.Mom (num_x-1,j,k);

      end loop;

   end set_constraints_bndry_fb;

   procedure set_constraints is
   begin

      set_finite_diff_factors;

      set_constraints_intr;
      set_constraints_bndry_fb;
      set_constraints_bndry_ew;
      set_constraints_bndry_ns;

   end set_constraints;

end BSSNBase.Constraints;
-- end: ./bssnbase-constraints.adt
